name: sajgoj_final
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  share: ^2.0.4
  url_launcher: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_rating_bar: ^3.2.0
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "images/Logo/app icon.png"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/Icons/a1.png
    - images/Icons/a2.png
    - images/Icons/a3.png
    - images/Icons/a4.png
    - images/Icons/a5.png
    - images/Icons/a6.png
    - images/Icons/a7.png
    - images/Icons/a8.png
    - images/Offer Picture/1.png
    - images/Offer Picture/4.jpg
    - images/Offer Picture/5.png
    - images/Offer Picture/7.jpg
    - images/Offer Picture/9.png
    - images/Offer Picture/offer.jpg
    - images/Product Images/Fragrance/a1.jpg #Fragrance product
    - images/Product Images/Fragrance/a2.jpg
    - images/Product Images/Fragrance/a3.jpg
    - images/Product Images/Fragrance/a4.jpg
    - images/Product Images/Fragrance/a5.jpg
    - images/Product Images/Personal Care/a1.jpg #Personal Care
    - images/Product Images/Personal Care/a2.jpg
    - images/Product Images/Personal Care/a3.jpg
    - images/Product Images/Personal Care/a4.jpg
    - images/Product Images/Personal Care/a5.png
    - images/Product Images/Natural/a1.jpg #Natureal
    - images/Product Images/Natural/a2.jpg
    - images/Product Images/Natural/a3.png
    - images/Product Images/Natural/a4.jpg
    - images/Product Images/Natural/a5.jpg
    - images/Product Images/Mom & Baby/a1.jpg #Mom and Baby
    - images/Product Images/Mom & Baby/a2.jpg
    - images/Product Images/Mom & Baby/a3.jpg
    - images/Product Images/Mom & Baby/a4.png
    - images/Product Images/Mom & Baby/a5.jpg
    - images/Product Images/Mom & Baby/a6.jpg
    - images/Product Images/Mom & Baby/a7.jpg
    - images/Product Images/Mom & Baby/a8.jpg
    - images/Product Images/Mom & Baby/a9.jpg
    - images/Product Images/Mom & Baby/a10.jpg
    - images/Product Images/Lipstick/a1.jpg #Lipstick
    - images/Product Images/Lipstick/a2.jpg
    - images/Product Images/Lipstick/a3.jpg
    - images/Product Images/Lipstick/a4.jpg
    - images/Product Images/Lipstick/a5.jpg
    - images/Product Images/Lipstick/a6.jpg
    - images/Product Images/Lipstick/a7.jpg
    - images/Product Images/Lipstick/a8.jpg
    - images/Product Images/Lipstick/a9.jpg
    - images/Product Images/Lipstick/a10.jpg
    - images/Product Images/Hair Care/c1.jpg  #Hair Care
    - images/Product Images/Hair Care/c2.jpg
    - images/Product Images/Hair Care/d1.png
    - images/Product Images/Hair Care/e1.jpg
    - images/Product Images/Hair Care/f1.jpg
    - images/Product Images/Hair Care/g1.jpg
    - images/Product Images/Hair Care/h1.jpg
    - images/Product Images/Hair Care/h2.jpg
    - images/Product Images/Hair Care/h3.jpg
    - images/Product Images/Hair Care/i1.jpg
    - images/Product Images/Hair Care/j1.jpg
    - images/Product Images/Hair Care/j2.jpg
    - images/Product Images/Hair Care/k1.jpg
    - images/Product Images/Hair Care/k2.jpg
    - images/Product Images/Hair Care/k3.jpg
    - images/Product Images/Makeup/a1.jpg #MakeUp
    - images/Product Images/Makeup/b1.jpg
    - images/Product Images/Makeup/c1.jpg
    - images/Product Images/Makeup/d1.jpg
    - images/Product Images/Makeup/e1.jpg
    - images/Product Images/Makeup/f1.jpg
    - images/Product Images/Makeup/g1.jpg
    - images/Product Images/Makeup/h1.jpg
    - images/Product Images/Makeup/i1.jpg
    - images/Product Images/Makeup/k1.jpg
    - images/Logo/sslogo.png #ss logo
    - images/Logo/
    - images/chlider images/ss1.png #chlider images
    - images/chlider images/ss2.png
    - images/chlider images/ss3.png
    - images/chlider images/ss4.png
    - images/Home Page images/01.png #Home page images
    - images/Home Page images/02.png
    - images/Home Page images/03.png
    - images/Home Page images/04.png
    - images/Home Page images/05.png
    - images/Home Page images/ls.png
    - images/category image/F.png #category images
    - images/category image/H.png
    - images/category image/LS.png
    - images/category image/M.png
    - images/category image/MB.png
    - images/category image/NT.png
    - images/category image/PC.png
    - images/category image/PC.png
    - images/category image/SK.png


  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
